[package]
name = "appletheia"
description = "The Application Interfaces for Event-Sourcing Architecture"
version = "0.9.0"
edition = "2024"
license = "MIT"
include = ["src/**", "Cargo.toml", "README.md", "LICENSE"]
authors = ["pbandj082 <pbandj082@gmail.com>"]
repository = "https://github.com/Lethephobia/appletheia"
keywords = ["appletheia", "ddd", "event-sourcing", "cqrs"]

[features]
default = []
domain = ["dep:appletheia-domain"]
application = ["dep:appletheia-application"]
macros-domain = ["dep:appletheia-macros", "domain"]
macros-application = ["dep:appletheia-macros", "application"]
infrastructure = ["dep:appletheia-infrastructure"]
infrastructure-cloud-events = ["infrastructure", "appletheia-infrastructure/cloud-events"]
infrastructure-http = ["infrastructure", "appletheia-infrastructure/http"]
infrastructure-jwt = ["infrastructure", "appletheia-infrastructure/jwt"]
infrastructure-sha = ["infrastructure", "appletheia-infrastructure/sha"]
infrastructure-aes-gcm = ["infrastructure", "appletheia-infrastructure/aes-gcm"]
infrastructure-postgresql = ["infrastructure", "appletheia-infrastructure/postgresql"]
infrastructure-google-cloud-pubsub = ["infrastructure", "appletheia-infrastructure/google-cloud-pubsub"]
infrastructure-google-cloud-storage = ["infrastructure", "appletheia-infrastructure/google-cloud-storage"]
full = ["domain", "application", "infrastructure", "appletheia-infrastructure/full", "macros-domain", "macros-application"]

[dependencies]
appletheia-domain = { workspace = true, optional = true }
appletheia-application = { workspace = true, optional = true }
appletheia-infrastructure = { workspace = true, optional = true }
appletheia-macros = { workspace = true, optional = true }
