mod organization_picture_object_delete_command;
mod organization_picture_object_delete_command_handler;
mod organization_picture_object_delete_command_handler_error;
mod organization_picture_object_delete_output;

pub use organization_picture_object_delete_command::OrganizationPictureObjectDeleteCommand;
pub use organization_picture_object_delete_command_handler::OrganizationPictureObjectDeleteCommandHandler;
pub use organization_picture_object_delete_command_handler_error::OrganizationPictureObjectDeleteCommandHandlerError;
pub use organization_picture_object_delete_output::OrganizationPictureObjectDeleteOutput;
