[package]
name = "banking-ledger-application"
version = "0.1.0"
edition = "2024"

[dependencies]
appletheia = { workspace = true, features = ["application", "macros-application"] }
banking-iam-application = { workspace = true }
banking-iam-domain = { workspace = true }
banking-ledger-domain = { workspace = true }
banking-shared-kernel-application = { workspace = true }
banking-shared-kernel-domain = { workspace = true }
base64 = "0.23.1"
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v7"] }

[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
