[package]
name = "banking-ledger-application"
version = "0.1.0"
edition = "2024"

[dependencies]
appletheia = { workspace = true, features = ["application", "macros-application"] }
banking-iam-application = { workspace = true }
banking-iam-domain = { workspace = true }
banking-ledger-domain = { workspace = true }
banking-shared-kernel-application = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v7"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
