[package]
name = "banking-ledger-infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
appletheia = { workspace = true, features = ["infrastructure"] }
banking-iam-domain = { workspace = true }
banking-ledger-application = { workspace = true }
banking-ledger-domain = { workspace = true }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "uuid", "chrono"] }
uuid = { version = "1" }
