[package]
name = "banking-iam-infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
appletheia = { workspace = true, features = ["application", "domain", "infrastructure"] }
banking-iam-domain = { workspace = true }
banking-iam-application = { workspace = true }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "postgres", "uuid", "chrono"] }
thiserror = "2.0.18"
uuid = { version = "1.23.2" }
