[features]
resolution = true
skip-lint = false

[programs.localnet]
banking_settlement = "DzYXFRU9PyJiEWLGaTQ8FA35urAtTkLH3G3QvQqMB2tZ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
