mod organization_invitation_list_criteria;
mod organization_invitation_list_cursor;
mod organization_invitation_list_invitee;
mod organization_invitation_list_invitee_upsert;
mod organization_invitation_list_issuer;
mod organization_invitation_list_item;
mod organization_invitation_list_item_status;
mod organization_invitation_list_organization;
mod organization_invitation_list_organization_upsert;
mod organization_invitation_list_reader;
mod organization_invitation_list_reader_error;
mod organization_invitation_list_sort_key;
mod organization_invitation_list_upsert;
mod organization_invitation_list_writer;
mod organization_invitation_list_writer_error;

pub use organization_invitation_list_criteria::OrganizationInvitationListCriteria;
pub use organization_invitation_list_cursor::OrganizationInvitationListCursor;
pub use organization_invitation_list_invitee::OrganizationInvitationListInvitee;
pub use organization_invitation_list_invitee_upsert::OrganizationInvitationListInviteeUpsert;
pub use organization_invitation_list_issuer::OrganizationInvitationListIssuer;
pub use organization_invitation_list_item::OrganizationInvitationListItem;
pub use organization_invitation_list_item_status::OrganizationInvitationListItemStatus;
pub use organization_invitation_list_organization::OrganizationInvitationListOrganization;
pub use organization_invitation_list_organization_upsert::OrganizationInvitationListOrganizationUpsert;
pub use organization_invitation_list_reader::OrganizationInvitationListReader;
pub use organization_invitation_list_reader_error::OrganizationInvitationListReaderError;
pub use organization_invitation_list_sort_key::OrganizationInvitationListSortKey;
pub use organization_invitation_list_upsert::OrganizationInvitationListUpsert;
pub use organization_invitation_list_writer::OrganizationInvitationListWriter;
pub use organization_invitation_list_writer_error::OrganizationInvitationListWriterError;

/// Read model for organization-scoped invitation list reads.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OrganizationInvitationList {
    pub organization: OrganizationInvitationListOrganization,
    pub items: Vec<OrganizationInvitationListItem>,
    pub next_cursor: Option<OrganizationInvitationListCursor>,
}
