mod organization_member_list_criteria;
mod organization_member_list_cursor;
mod organization_member_list_item;
mod organization_member_list_member;
mod organization_member_list_member_upsert;
mod organization_member_list_membership_upsert;
mod organization_member_list_organization;
mod organization_member_list_organization_upsert;
mod organization_member_list_reader;
mod organization_member_list_reader_error;
mod organization_member_list_sort_key;
mod organization_member_list_writer;
mod organization_member_list_writer_error;

pub use organization_member_list_criteria::OrganizationMemberListCriteria;
pub use organization_member_list_cursor::OrganizationMemberListCursor;
pub use organization_member_list_item::OrganizationMemberListItem;
pub use organization_member_list_member::OrganizationMemberListMember;
pub use organization_member_list_member_upsert::OrganizationMemberListMemberUpsert;
pub use organization_member_list_membership_upsert::OrganizationMemberListMembershipUpsert;
pub use organization_member_list_organization::OrganizationMemberListOrganization;
pub use organization_member_list_organization_upsert::OrganizationMemberListOrganizationUpsert;
pub use organization_member_list_reader::OrganizationMemberListReader;
pub use organization_member_list_reader_error::OrganizationMemberListReaderError;
pub use organization_member_list_sort_key::OrganizationMemberListSortKey;
pub use organization_member_list_writer::OrganizationMemberListWriter;
pub use organization_member_list_writer_error::OrganizationMemberListWriterError;

/// Read model for organization member list reads.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OrganizationMemberList {
    pub organization: OrganizationMemberListOrganization,
    pub items: Vec<OrganizationMemberListItem>,
    pub next_cursor: Option<OrganizationMemberListCursor>,
}
