mod user_organization_join_request_list_criteria;
mod user_organization_join_request_list_cursor;
mod user_organization_join_request_list_item;
mod user_organization_join_request_list_item_status;
mod user_organization_join_request_list_organization;
mod user_organization_join_request_list_organization_upsert;
mod user_organization_join_request_list_reader;
mod user_organization_join_request_list_reader_error;
mod user_organization_join_request_list_sort_key;
mod user_organization_join_request_list_upsert;
mod user_organization_join_request_list_user;
mod user_organization_join_request_list_user_upsert;
mod user_organization_join_request_list_writer;
mod user_organization_join_request_list_writer_error;

pub use user_organization_join_request_list_criteria::UserOrganizationJoinRequestListCriteria;
pub use user_organization_join_request_list_cursor::UserOrganizationJoinRequestListCursor;
pub use user_organization_join_request_list_item::UserOrganizationJoinRequestListItem;
pub use user_organization_join_request_list_item_status::UserOrganizationJoinRequestListItemStatus;
pub use user_organization_join_request_list_organization::UserOrganizationJoinRequestListOrganization;
pub use user_organization_join_request_list_organization_upsert::UserOrganizationJoinRequestListOrganizationUpsert;
pub use user_organization_join_request_list_reader::UserOrganizationJoinRequestListReader;
pub use user_organization_join_request_list_reader_error::UserOrganizationJoinRequestListReaderError;
pub use user_organization_join_request_list_sort_key::UserOrganizationJoinRequestListSortKey;
pub use user_organization_join_request_list_upsert::UserOrganizationJoinRequestListUpsert;
pub use user_organization_join_request_list_user::UserOrganizationJoinRequestListUser;
pub use user_organization_join_request_list_user_upsert::UserOrganizationJoinRequestListUserUpsert;
pub use user_organization_join_request_list_writer::UserOrganizationJoinRequestListWriter;
pub use user_organization_join_request_list_writer_error::UserOrganizationJoinRequestListWriterError;

/// Read model for user-scoped organization join request list reads.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UserOrganizationJoinRequestList {
    pub user: UserOrganizationJoinRequestListUser,
    pub items: Vec<UserOrganizationJoinRequestListItem>,
    pub next_cursor: Option<UserOrganizationJoinRequestListCursor>,
}
