mod user_organization_invitation_list_criteria;
mod user_organization_invitation_list_cursor;
mod user_organization_invitation_list_issuer;
mod user_organization_invitation_list_item;
mod user_organization_invitation_list_item_status;
mod user_organization_invitation_list_organization;
mod user_organization_invitation_list_organization_upsert;
mod user_organization_invitation_list_reader;
mod user_organization_invitation_list_reader_error;
mod user_organization_invitation_list_sort_key;
mod user_organization_invitation_list_upsert;
mod user_organization_invitation_list_user;
mod user_organization_invitation_list_user_upsert;
mod user_organization_invitation_list_writer;
mod user_organization_invitation_list_writer_error;

pub use user_organization_invitation_list_criteria::UserOrganizationInvitationListCriteria;
pub use user_organization_invitation_list_cursor::UserOrganizationInvitationListCursor;
pub use user_organization_invitation_list_issuer::UserOrganizationInvitationListIssuer;
pub use user_organization_invitation_list_item::UserOrganizationInvitationListItem;
pub use user_organization_invitation_list_item_status::UserOrganizationInvitationListItemStatus;
pub use user_organization_invitation_list_organization::UserOrganizationInvitationListOrganization;
pub use user_organization_invitation_list_organization_upsert::UserOrganizationInvitationListOrganizationUpsert;
pub use user_organization_invitation_list_reader::UserOrganizationInvitationListReader;
pub use user_organization_invitation_list_reader_error::UserOrganizationInvitationListReaderError;
pub use user_organization_invitation_list_sort_key::UserOrganizationInvitationListSortKey;
pub use user_organization_invitation_list_upsert::UserOrganizationInvitationListUpsert;
pub use user_organization_invitation_list_user::UserOrganizationInvitationListUser;
pub use user_organization_invitation_list_user_upsert::UserOrganizationInvitationListUserUpsert;
pub use user_organization_invitation_list_writer::UserOrganizationInvitationListWriter;
pub use user_organization_invitation_list_writer_error::UserOrganizationInvitationListWriterError;

/// Read model for user-scoped organization invitation list reads.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct UserOrganizationInvitationList {
    pub user: UserOrganizationInvitationListUser,
    pub items: Vec<UserOrganizationInvitationListItem>,
    pub next_cursor: Option<UserOrganizationInvitationListCursor>,
}
