use appletheia::domain::{EventId, EventOccurredAt};
use banking_ledger_domain::account::{AccountId, AccountOwner};
use banking_ledger_domain::core::CurrencyAmount;

mod owned_account_transaction_list_item_counterparty_account;
mod owned_account_transaction_list_item_counterparty_account_owner;
mod owned_account_transaction_list_item_counterparty_account_owner_organization;
mod owned_account_transaction_list_item_counterparty_account_owner_user;
mod owned_account_transaction_list_item_currency;
mod owned_account_transaction_list_item_cursor;
mod owned_account_transaction_list_item_direction;
mod owned_account_transaction_list_item_kind;
mod owned_account_transaction_list_item_reader;
mod owned_account_transaction_list_item_reader_error;
mod owned_account_transaction_list_item_sort_key;
mod owned_account_transaction_list_item_status;
mod owned_account_transaction_list_item_writer;
mod owned_account_transaction_list_item_writer_error;

pub use owned_account_transaction_list_item_counterparty_account::OwnedAccountTransactionListItemCounterpartyAccount;
pub use owned_account_transaction_list_item_counterparty_account_owner::OwnedAccountTransactionListItemCounterpartyAccountOwner;
pub use owned_account_transaction_list_item_counterparty_account_owner_organization::OwnedAccountTransactionListItemCounterpartyAccountOwnerOrganization;
pub use owned_account_transaction_list_item_counterparty_account_owner_user::OwnedAccountTransactionListItemCounterpartyAccountOwnerUser;
pub use owned_account_transaction_list_item_currency::OwnedAccountTransactionListItemCurrency;
pub use owned_account_transaction_list_item_cursor::OwnedAccountTransactionListItemCursor;
pub use owned_account_transaction_list_item_direction::OwnedAccountTransactionListItemDirection;
pub use owned_account_transaction_list_item_kind::OwnedAccountTransactionListItemKind;
pub use owned_account_transaction_list_item_reader::OwnedAccountTransactionListItemReader;
pub use owned_account_transaction_list_item_reader_error::OwnedAccountTransactionListItemReaderError;
pub use owned_account_transaction_list_item_sort_key::OwnedAccountTransactionListItemSortKey;
pub use owned_account_transaction_list_item_status::OwnedAccountTransactionListItemStatus;
pub use owned_account_transaction_list_item_writer::OwnedAccountTransactionListItemWriter;
pub use owned_account_transaction_list_item_writer_error::OwnedAccountTransactionListItemWriterError;

/// Read model for one owned account transaction list row.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OwnedAccountTransactionListItem {
    pub id: EventId,
    pub owner: AccountOwner,
    pub account_id: AccountId,
    pub currency: OwnedAccountTransactionListItemCurrency,
    pub amount: CurrencyAmount,
    pub direction: OwnedAccountTransactionListItemDirection,
    pub kind: OwnedAccountTransactionListItemKind,
    pub status: OwnedAccountTransactionListItemStatus,
    pub occurred_at: EventOccurredAt,
    pub created_at: EventOccurredAt,
}
