use appletheia::application::read_model::{ReadModel, ReadModelName};
use serde::Serialize;

mod owned_account_transaction_id;
mod owned_account_transaction_list_criteria;
mod owned_account_transaction_list_cursor;
mod owned_account_transaction_list_item;
mod owned_account_transaction_list_item_counterparty_account;
mod owned_account_transaction_list_item_counterparty_account_owner;
mod owned_account_transaction_list_item_counterparty_account_owner_organization;
mod owned_account_transaction_list_item_counterparty_account_owner_user;
mod owned_account_transaction_list_item_currency;
mod owned_account_transaction_list_item_direction;
mod owned_account_transaction_list_item_kind;
mod owned_account_transaction_list_item_status;
mod owned_account_transaction_list_owner;
mod owned_account_transaction_list_owner_organization;
mod owned_account_transaction_list_owner_user;
mod owned_account_transaction_list_reader;
mod owned_account_transaction_list_reader_error;
mod owned_account_transaction_list_sort_key;

pub use owned_account_transaction_id::OwnedAccountTransactionId;
pub use owned_account_transaction_list_criteria::OwnedAccountTransactionListCriteria;
pub use owned_account_transaction_list_cursor::OwnedAccountTransactionListCursor;
pub use owned_account_transaction_list_item::OwnedAccountTransactionListItem;
pub use owned_account_transaction_list_item_counterparty_account::OwnedAccountTransactionListItemCounterpartyAccount;
pub use owned_account_transaction_list_item_counterparty_account_owner::OwnedAccountTransactionListItemCounterpartyAccountOwner;
pub use owned_account_transaction_list_item_counterparty_account_owner_organization::OwnedAccountTransactionListItemCounterpartyAccountOwnerOrganization;
pub use owned_account_transaction_list_item_counterparty_account_owner_user::OwnedAccountTransactionListItemCounterpartyAccountOwnerUser;
pub use owned_account_transaction_list_item_currency::OwnedAccountTransactionListItemCurrency;
pub use owned_account_transaction_list_item_direction::OwnedAccountTransactionListItemDirection;
pub use owned_account_transaction_list_item_kind::OwnedAccountTransactionListItemKind;
pub use owned_account_transaction_list_item_status::OwnedAccountTransactionListItemStatus;
pub use owned_account_transaction_list_owner::OwnedAccountTransactionListOwner;
pub use owned_account_transaction_list_owner_organization::OwnedAccountTransactionListOwnerOrganization;
pub use owned_account_transaction_list_owner_user::OwnedAccountTransactionListOwnerUser;
pub use owned_account_transaction_list_reader::OwnedAccountTransactionListReader;
pub use owned_account_transaction_list_reader_error::OwnedAccountTransactionListReaderError;
pub use owned_account_transaction_list_sort_key::OwnedAccountTransactionListSortKey;

/// Read model for owned account transaction list reads.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct OwnedAccountTransactionList {
    pub owner: OwnedAccountTransactionListOwner,
    pub items: Vec<OwnedAccountTransactionListItem>,
    pub start_cursor: Option<OwnedAccountTransactionListCursor>,
    pub end_cursor: Option<OwnedAccountTransactionListCursor>,
    pub has_previous: bool,
    pub has_next: bool,
}

impl ReadModel for OwnedAccountTransactionList {
    const NAME: ReadModelName = ReadModelName::new("owned_account_transaction_list");
}
