pub mod command_attempt_count;
pub mod command_attempt_count_error;
pub mod command_dispatch_result;
pub mod command_dispatcher;
pub mod command_dispatcher_error;
pub mod command_envelope;
pub mod command_envelope_error;
pub mod command_execution_failure_mark_result;
pub mod command_execution_id;
pub mod command_execution_id_error;
pub mod command_execution_lease_acquisition_result;
pub mod command_execution_lease_duration;
pub mod command_execution_lease_release_result;
pub mod command_execution_max_attempts;
pub mod command_execution_retry_options;
pub mod command_execution_store;
pub mod command_execution_store_error;
pub mod command_failed_at;
pub mod command_failure_envelope;
pub mod command_failure_id;
pub mod command_failure_id_error;
pub mod command_handler;
pub mod command_hash;
pub mod command_hash_error;
pub mod command_hasher;
pub mod command_hasher_error;
pub mod command_name;
pub mod command_name_owned;
pub mod command_name_owned_error;
pub mod command_options;
pub mod command_output;
pub mod command_replay_output;
pub mod command_selector;
pub mod command_terminal_reason;
pub mod command_worker;
pub mod command_worker_config;
pub mod command_worker_error;
pub mod default_command_dispatcher;
pub mod default_command_worker;
pub mod default_command_worker_dependencies;
pub mod field_patch;
pub mod idempotency_begin_result;
pub mod idempotency_id;
pub mod idempotency_id_error;
pub mod idempotency_output;
pub mod idempotency_output_error;
pub mod idempotency_service;
pub mod idempotency_service_error;
pub mod serialized_command;
pub mod serialized_command_error;

pub use command_attempt_count::CommandAttemptCount;
pub use command_attempt_count_error::CommandAttemptCountError;
pub use command_dispatch_result::CommandDispatchResult;
pub use command_dispatcher::CommandDispatcher;
pub use command_dispatcher_error::CommandDispatcherError;
pub use command_envelope::CommandEnvelope;
pub use command_envelope_error::CommandEnvelopeError;
pub use command_execution_failure_mark_result::CommandExecutionFailureMarkResult;
pub use command_execution_id::CommandExecutionId;
pub use command_execution_id_error::CommandExecutionIdError;
pub use command_execution_lease_acquisition_result::CommandExecutionLeaseAcquisitionResult;
pub use command_execution_lease_duration::CommandExecutionLeaseDuration;
pub use command_execution_lease_release_result::CommandExecutionLeaseReleaseResult;
pub use command_execution_max_attempts::CommandExecutionMaxAttempts;
pub use command_execution_retry_options::CommandExecutionRetryOptions;
pub use command_execution_store::CommandExecutionStore;
pub use command_execution_store_error::CommandExecutionStoreError;
pub use command_failed_at::CommandFailedAt;
pub use command_failure_envelope::CommandFailureEnvelope;
pub use command_failure_id::CommandFailureId;
pub use command_failure_id_error::CommandFailureIdError;
pub use command_handler::CommandHandler;
pub use command_hash::CommandHash;
pub use command_hash_error::CommandHashError;
pub use command_hasher::CommandHasher;
pub use command_hasher_error::CommandHasherError;
pub use command_name::CommandName;
pub use command_name_owned::CommandNameOwned;
pub use command_name_owned_error::CommandNameOwnedError;
pub use command_options::CommandOptions;
pub use command_output::CommandOutput;
pub use command_replay_output::CommandReplayOutput;
pub use command_selector::CommandSelector;
pub use command_terminal_reason::CommandTerminalReason;
pub use command_worker::CommandWorker;
pub use command_worker_config::CommandWorkerConfig;
pub use command_worker_error::CommandWorkerError;
pub use default_command_dispatcher::DefaultCommandDispatcher;
pub use default_command_worker::DefaultCommandWorker;
pub use default_command_worker_dependencies::DefaultCommandWorkerDependencies;
pub use field_patch::FieldPatch;
pub use idempotency_begin_result::IdempotencyBeginResult;
pub use idempotency_id::IdempotencyId;
pub use idempotency_id_error::IdempotencyIdError;
pub use idempotency_output::IdempotencyOutput;
pub use idempotency_output_error::IdempotencyOutputError;
pub use idempotency_service::IdempotencyService;
pub use idempotency_service_error::IdempotencyServiceError;
pub use serialized_command::SerializedCommand;
pub use serialized_command_error::SerializedCommandError;

use serde::Serialize;
use serde::de::DeserializeOwned;

/// Represents an application command that can be dispatched through the command pipeline.
///
/// `NAME` must remain stable for the command type so infrastructure can identify the
/// command consistently across routing, persistence, and replay boundaries.
pub trait Command: Serialize + DeserializeOwned + Send + 'static {
    /// Returns the stable identifier for the command type.
    const NAME: CommandName;
}
