pub mod command_attempt_count;
pub mod command_attempt_count_error;
pub mod command_dispatch_result;
pub mod command_dispatcher;
pub mod command_dispatcher_error;
pub mod command_envelope;
pub mod command_envelope_error;
pub mod command_execution_failure_mark_result;
pub mod command_execution_id;
pub mod command_execution_id_error;
pub mod command_execution_lease_acquisition_result;
pub mod command_execution_lease_duration;
pub mod command_execution_lease_release_result;
pub mod command_execution_max_attempts;
pub mod command_execution_retry_options;
pub mod command_execution_store;
pub mod command_execution_store_error;
pub mod command_failed_at;
pub mod command_failure_envelope;
pub mod command_failure_envelope_error;
pub mod command_failure_id;
pub mod command_failure_id_error;
pub mod command_handler;
pub mod command_hash;
pub mod command_hash_error;
pub mod command_hasher;
pub mod command_hasher_error;
pub mod command_name;
pub mod command_name_owned;
pub mod command_name_owned_error;
pub mod command_options;
pub mod command_output;
pub mod command_replay_output;
pub mod command_selector;
pub mod command_terminal_reason;
pub mod command_worker;
pub mod command_worker_config;
pub mod command_worker_error;
pub mod default_command_dispatcher;
pub mod default_command_worker;
pub mod default_command_worker_dependencies;
pub mod field_patch;
pub mod idempotency_begin_result;
pub mod idempotency_id;
pub mod idempotency_id_error;
pub mod idempotency_output;
pub mod idempotency_output_error;
pub mod idempotency_service;
pub mod idempotency_service_error;
pub mod serialized_command;
pub mod serialized_command_error;

pub use command_attempt_count::*;
pub use command_attempt_count_error::*;
pub use command_dispatch_result::*;
pub use command_dispatcher::*;
pub use command_dispatcher_error::*;
pub use command_envelope::*;
pub use command_envelope_error::*;
pub use command_execution_failure_mark_result::*;
pub use command_execution_id::*;
pub use command_execution_id_error::*;
pub use command_execution_lease_acquisition_result::*;
pub use command_execution_lease_duration::*;
pub use command_execution_lease_release_result::*;
pub use command_execution_max_attempts::*;
pub use command_execution_retry_options::*;
pub use command_execution_store::*;
pub use command_execution_store_error::*;
pub use command_failed_at::*;
pub use command_failure_envelope::*;
pub use command_failure_envelope_error::*;
pub use command_failure_id::*;
pub use command_failure_id_error::*;
pub use command_handler::*;
pub use command_hash::*;
pub use command_hash_error::*;
pub use command_hasher::*;
pub use command_hasher_error::*;
pub use command_name::*;
pub use command_name_owned::*;
pub use command_name_owned_error::*;
pub use command_options::*;
pub use command_output::*;
pub use command_replay_output::*;
pub use command_selector::*;
pub use command_terminal_reason::*;
pub use command_worker::*;
pub use command_worker_config::*;
pub use command_worker_error::*;
pub use default_command_dispatcher::*;
pub use default_command_worker::*;
pub use default_command_worker_dependencies::*;
pub use field_patch::*;
pub use idempotency_begin_result::*;
pub use idempotency_id::*;
pub use idempotency_id_error::*;
pub use idempotency_output::*;
pub use idempotency_output_error::*;
pub use idempotency_service::*;
pub use idempotency_service_error::*;
pub use serialized_command::*;
pub use serialized_command_error::*;

use serde::Serialize;
use serde::de::DeserializeOwned;

/// Represents an application command that can be dispatched through the command pipeline.
///
/// `NAME` must remain stable for the command type so infrastructure can identify the
/// command consistently across routing, persistence, and replay boundaries.
pub trait Command: Serialize + DeserializeOwned + Send + 'static {
    /// Returns the stable identifier for the command type.
    const NAME: CommandName;
}
