[package]
name = "appletheia-domain"
version = "0.1.0"
edition = "2024"
include = ["src/**", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
chrono = "0.4.42"
thiserror = "2.0.17"
uuid = { version = "1.18.1", features = ["v7"] }
