name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build root workspace
      run: cargo build --verbose
    - name: Run root workspace tests
      run: cargo test --verbose
    - name: Build banking server workspace
      run: cargo build --manifest-path examples/banking/server/Cargo.toml --verbose
    - name: Run banking server workspace tests
      run: cargo test --manifest-path examples/banking/server/Cargo.toml --verbose
