[package]
name = "appletheia-application"
description = "The Application Layer for Event-Sourcing Architecture"
version = "0.1.0"
edition = "2024"
license = "MIT"
include = ["src/**", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
appletheia-domain = { version = "0.1.0", path = "../appletheia-domain" }
